FROM ubuntu:14.04.3

RUN apt-get update && apt-get install -y libmysqlclient-dev    \
    build-essential zlib1g-dev libc6-dev libc-dev gcc g++      \
    cpp libpng-dev libpng12-dev libsdl-image1.2-dev zlib1g-dev \
    libssl-dev rsync

WORKDIR /src
